Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty32"

  config.vm.provider :virtualbox do |v|
     v.customize ["modifyvm", :id, "--memory", 1024]
  end

  config.ssh.forward_agent = false
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.synced_folder "./../", "/home/vagrant/battle-balancer"
  config.vm.provision :shell do |shell|
    shell.path = "bootstrap.sh"
  end
end